name: Build Artifacts

on:
  push:
    branches:
      - master
  pull_request:

  #manual triggering
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x lint

    - name: Copy Release Artifacts
      run: |
        mkdir -p geopackage-map/build/release
        cp geopackage-map/build/libs/*.jar geopackage-map/build/outputs/aar/geopackage-android-map-release.aar geopackage-map/build/release/
        VERSION=$(grep -E "^\s*version\s*=" build.gradle | sed 's/[a-z ="]//g')
        mv "geopackage-map/build/release/geopackage-android-map-release.aar" "geopackage-map/build/release/geopackage-android-map-${VERSION}.aar"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: geopackage-android-map
        path: geopackage-map/build/release
